# Development Profile

 # H2 Console enabled
 spring.h2.console.enabled=true

 # Show SQL queries
 spring.jpa.show-sql=true

 # Hot reload enabled
 spring.devtools.restart.enabled=true

 # Thymeleaf cache disabled for live reload
 spring.thymeleaf.cache=false

 # Detailed logging
 logging.level.com.crudzaso.MobileFix=DEBUG